### PR TITLE
Fix reproducible build

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by heiher** [comment]
Thank you.

**Comment by heiher** [comment]
Oops. This patch breaks basic functionality. @linsui

**Comment by heiher** [comment]
Resolved by https://github.com/heiher/sockstun/releases/tag/2.5

**Comment by linsui** [comment]
Oh, sorry! Can you bump the versionCode so that F-Droid can pick the new version?

**Comment by heiher** [comment]
> Oh, sorry! Can you bump the versionCode so that F-Droid can pick the new version?

Okay, I'll force update it.

**Comment by heiher** [comment]
> Oh, sorry! Can you bump the versionCode so that F-Droid can pick the new version?

It's done.

**Comment by linsui** [comment]
Thanks!

**Pull request merged**
